services:
  postgres-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: TheNewCantina
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d TheNewCantina"]
      interval: 5s
      timeout: 5s
      retries: 6


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ../docker-data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres-db
 
  python-app:
    container_name: python-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
        - "8081:5045"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata: