services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: TheNewCantina
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      TZ: Europe/Paris

    # Datas access from the host
    volumes:
      - ../db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres-db
 
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
        - "8081:5045"
    depends_on:
      - postgres-db