# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOrderfoodinthepast():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_orderfoodinthepast(self):
    self.driver.get("http://localhost:8081/login")
    self.driver.set_window_size(1512, 888)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("student1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("pass123")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Kafeteria").click()
    self.driver.find_element(By.LINK_TEXT, "Letisko Hričov").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(11) > .w-8").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dark\\3A bg-slate-700\\/50").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .w-8").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .w-8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-slate-50:nth-child(4) .inline-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-blue-700").click()
    self.driver.find_element(By.LINK_TEXT, "Order History").click()
  
